server.port=8082

max.bot.token=f9LHodD0cOKwvFQbGW-wvhdW5NikT6e6MZmZVJsLNfnH-c_F0LDl6Aw6pPdeLsjUveLInivqiQDsmZa3sI3Y
notifications.chat.id=-75961517897960
site.url=https://themave.ru

spring.ai.openai.base-url=https://api.deepseek.com
spring.ai.openai.api-key=sk-c2b897376c7543f1b9ed43804946ae93
spring.ai.openai.chat.options.model=deepseek-chat

logging.level.ru.mave.maveshopbot=INFO