server.port=8082

max.bot.token=f9LHodD0cOKwvFQbGW-wvhdW5NikT6e6MZmZVJsLNfnH-c_F0LDl6Aw6pPdeLsjUveLInivqiQDsmZa3sI3Y
notifications.chat.id=-75757705197800

site.url=https://themave.ru

logging.level.ru.mave.maveshopbot=INFO